public_s3:
  service: PublicS3
  access_key_id: <%= ENV["STORAGE_ACCESS_KEY_ID"] %>
  secret_access_key: <%= ENV["STORAGE_SECRET_ACCESS_KEY"] %>
  bucket: <%= ENV["STORAGE_BUCKET_NAME"] %>
  region: <%= ENV["STORAGE_REGION"] %>
  endpoint: <%= ENV["STORAGE_ENDPOINT"] %>
  force_path_style: true